{{- if .Values.frontend.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
  name: {{ include "frontend.fullname" . }}
  annotations:
    haproxy.router.openshift.io/timeout: {{ .Values.frontend.route.timeout }}
spec:
  host: {{ include "frontend.fullname" . }}.{{ .Values.global.domain }}
  port:
    targetPort: {{ .Values.frontend.route.targetPort }}
  to:
    kind: Service
    name: {{ include "frontend.fullname" . }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}