{{- if .Values.backend.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
{{- range $key, $value := .Values.backend.configMap.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}