{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  strategy:
    type: {{ .Values.backend.deploymentStrategy }}
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3000'
        prometheus.io/path: '/api/metrics'
      labels:
        {{- include "backend.labels" . | nindent 8 }}
    spec:
      {{- if .Values.backend.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 12 }}
      {{- end }}
      containers:
        - name: {{ include "backend.fullname" . }}
          {{- if .Values.backend.securityContext }}
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          {{- end }}
          image: "{{.Values.backend.image.registry}}/{{.Values.backend.image.repository}}/backend:{{.Values.backend.image.tag}}"
          imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
          envFrom:
            {{- if .Values.backend.configMap.enabled }}
            - configMapRef:
                name: {{ .Release.Name }}-config
            {{- end }}
          env:
            - name: LOG_LEVEL
              value: info
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-backend
                  key: POSTGRES_USER
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-database
                  key: password
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-backend
                  key: POSTGRES_DATABASE
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-backend
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-database
                  key: password
            - name: POSTGRES_HOST_READER
              value: {{ include "fullname" . }}-bitnamipg
            - name: POSTGRES_HOST_WRITER
              value: {{ include "fullname" . }}-bitnamipg
            - name: PGHOST
              value: {{ include "fullname" . }}-bitnamipg
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          # readinessProbe:
          #   httpGet:
          #     path: /api/health
          #     port: http
          #     scheme: HTTP
          #   initialDelaySeconds: 5
          #   periodSeconds: 2
          #   timeoutSeconds: 2
          #   successThreshold: 1
          #   failureThreshold: 30
          # livenessProbe:
          #   successThreshold: 1
          #   failureThreshold: 3
          #   httpGet:
          #     path: /api/health
          #     port: 3000
          #     scheme: HTTP
          #   initialDelaySeconds: 15
          #   periodSeconds: 30
          #   timeoutSeconds: 5
          resources: # this is optional
            requests:
              {{- toYaml .Values.backend.resources.requests | nindent 12 }}
            limits:
              {{- toYaml .Values.backend.resources.limits | nindent 12 }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "backend.fullname" . }}
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"

{{- end }}