{{- if .Values.backend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: database
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
{{- end }}